apiVersion: v1
kind: ConfigMap
metadata:
  name: init-sql
  namespace: ksec-edgeai
data:
  jimureport.mysql5.7.create.sql: |
    /*
     Navicat Premium Data Transfer

     Source Server         : localhost5.7
     Source Server Type    : MySQL
     Source Server Version : 50725
     Source Host           : localhost:3306
     Source Schema         : jimumysql

     Target Server Type    : MySQL
     Target Server Version : 50725
     File Encoding         : 65001

     Date: 28/05/2020 14:35:53
    */

    SET NAMES utf8mb4;
    SET FOREIGN_KEY_CHECKS = 0;

    -- ----------------------------
    -- Table structure for demo
    -- ----------------------------
    DROP TABLE IF EXISTS `demo`;
    CREATE TABLE `demo`  (
      `id` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
      `name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
      PRIMARY KEY (`id`) USING BTREE
    ) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

    -- ----------------------------
    -- Records of demo
    -- ----------------------------
    INSERT INTO `demo` VALUES ('123123', '123123');

    -- ----------------------------
    -- Table structure for jmreport_data_source
    -- ----------------------------
    DROP TABLE IF EXISTS `jmreport_data_source`;
    CREATE TABLE `jmreport_data_source`  (
      `id` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
      `db_code` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '数据源编码',
      `db_ch_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '数据源名称',
      `db_en_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '数据源英文名称',
      `db_type` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '数据库类型',
      `db_driver` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '驱动类',
      `db_url` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '数据源地址',
      `db_username` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '用户名',
      `db_password` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '密码',
      `db_encrypt` int(1) NULL DEFAULT NULL COMMENT '是否加密 0否 1是',
      `create_by` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '创建人',
      `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建日期',
      `update_by` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '更新人',
      `update_time` datetime(0) NULL DEFAULT NULL COMMENT '更新日期',
      `sys_org_code` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '所属部门编码',
      PRIMARY KEY (`id`) USING BTREE
    ) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_bin ROW_FORMAT = Dynamic;

    -- ----------------------------
    -- Records of jmreport_data_source
    -- ----------------------------
    INSERT INTO `jmreport_data_source` VALUES ('1220883392825888770', 'local', '本地数据库', 'local', 'MYSQL', 'com.mysql.cj.jdbc.Driver', 'jdbc:mysql://127.0.0.1:3306/jimureport?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false', 'root', 'root', 0, 'admin', '2020-01-21 15:35:18', 'admin', '2020-05-25 15:36:56', '北京国炬软件有限公司');

    -- ----------------------------
    -- Table structure for jmreport_data_source_dsn
    -- ----------------------------
    DROP TABLE IF EXISTS `jmreport_data_source_dsn`;
    CREATE TABLE `jmreport_data_source_dsn`  (
      `id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
      `db_ch_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '数据源名称',
      `db_type` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '数据库类型',
      `db_username` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '用户名',
      `db_password` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '密码',
      `db_url` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '链接地址',
      `create_by` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '创建人',
      `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
      `update_by` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '修改人',
      `update_time` datetime(0) NULL DEFAULT NULL COMMENT '修改时间',
      `sys_org_code` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '所属部门',
      `db_encrypt` int(1) NULL DEFAULT NULL COMMENT '是否加密 0否 1是',
      PRIMARY KEY (`id`) USING BTREE
    ) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

    -- ----------------------------
    -- Table structure for jmreport_order_info
    -- ----------------------------
    DROP TABLE IF EXISTS `jmreport_order_info`;
    CREATE TABLE `jmreport_order_info`  (
      `id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
      `order_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '订单名称',
      `order_code` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '订单编号',
      `order_price` double(10, 2) NULL DEFAULT NULL COMMENT '订单金额',
      `order_date` datetime(0) NULL DEFAULT NULL COMMENT '订单时间',
      `create_by` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '创建人',
      `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
      `update_by` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '修改人',
      `update_time` datetime(0) NULL DEFAULT NULL COMMENT '修改时间',
      `sys_org_code` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '所属部门',
      PRIMARY KEY (`id`) USING BTREE
    ) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

    -- ----------------------------
    -- Records of jmreport_order_info
    -- ----------------------------
    INSERT INTO `jmreport_order_info` VALUES ('1221978417394466818', '华为手机', 'SP001', 5000.00, '2020-01-24 16:06:06', 'admin', '2020-01-24 16:06:21', NULL, NULL, NULL);
    INSERT INTO `jmreport_order_info` VALUES ('1221978464528527362', '苹果手机', 'SP002', 8000.00, '2020-01-24 16:06:18', 'admin', '2020-01-24 16:06:32', NULL, NULL, NULL);
    INSERT INTO `jmreport_order_info` VALUES ('1221978507715588098', '小米手机', 'SP003', 2000.00, '2020-01-24 16:06:28', 'admin', '2020-01-24 16:06:42', NULL, NULL, NULL);
    INSERT INTO `jmreport_order_info` VALUES ('1221978547347947521', '魅族手机', 'SP004', 3000.00, '2020-01-24 16:06:37', 'admin', '2020-01-24 16:06:52', NULL, NULL, NULL);
    INSERT INTO `jmreport_order_info` VALUES ('1221978588359446530', '联想电脑', 'SP005', 6000.00, '2020-01-24 16:06:47', 'admin', '2020-01-24 16:07:01', NULL, NULL, NULL);
    INSERT INTO `jmreport_order_info` VALUES ('1221978631016005633', '戴尔电脑', 'SP006', 4000.00, '2020-01-24 16:06:57', 'admin', '2020-01-24 16:07:12', NULL, NULL, NULL);
    INSERT INTO `jmreport_order_info` VALUES ('1221978671289266177', '苹果电脑', 'SP007', 10000.00, '2020-01-24 16:07:07', 'admin', '2020-01-24 16:07:21', NULL, NULL, NULL);

    -- ----------------------------
    -- Table structure for jmreport_qurestion_info
    -- ----------------------------
    DROP TABLE IF EXISTS `jmreport_qurestion_info`;
    CREATE TABLE `jmreport_qurestion_info`  (
      `id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
      `question_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '问题名称',
      `question_content` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '问题内容',
      `create_by` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '创建人',
      `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
      `update_by` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '修改人',
      `update_time` datetime(0) NULL DEFAULT NULL COMMENT '修改时间',
      `sys_org_code` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '所属部门',
      PRIMARY KEY (`id`) USING BTREE
    ) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

    -- ----------------------------
    -- Records of jmreport_qurestion_info
    -- ----------------------------
    INSERT INTO `jmreport_qurestion_info` VALUES ('1221979202323587074', 'JIMU报表问题', 'JIMU报表支持哪些数据库？', 'admin', '2020-01-24 16:09:15', NULL, NULL, NULL);
    INSERT INTO `jmreport_qurestion_info` VALUES ('1221979260789170178', 'JIMU报表问题', 'JIMU报表支持哪些图表？', 'admin', '2020-01-24 16:09:29', NULL, NULL, NULL);
    INSERT INTO `jmreport_qurestion_info` VALUES ('1221979308772962306', 'JIMU报表问题', 'JIMU报表是否支持多数据源？', 'admin', '2020-01-24 16:09:40', NULL, NULL, NULL);
    INSERT INTO `jmreport_qurestion_info` VALUES ('1221979350576390146', 'JIMU报表问题', 'JIMU报表是否支持定时任务？', 'admin', '2020-01-24 16:09:50', NULL, NULL, NULL);
    INSERT INTO `jmreport_qurestion_info` VALUES ('1221979390188843009', 'JIMU报表问题', 'JIMU报表是否支持导出功能？', 'admin', '2020-01-24 16:10:00', NULL, NULL, NULL);

    -- ----------------------------
    -- Table structure for jmreport_test_user
    -- ----------------------------
    DROP TABLE IF EXISTS `jmreport_test_user`;
    CREATE TABLE `jmreport_test_user`  (
      `id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
      `name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '姓名',
      `age` int(3) NULL DEFAULT NULL COMMENT '年龄',
      `birthday` datetime(0) NULL DEFAULT NULL COMMENT '生日',
      `sex` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '性别',
      `salary` double(10, 2) NULL DEFAULT NULL COMMENT '薪资',
      `create_by` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '创建人',
      `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
      `update_by` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '修改人',
      `update_time` datetime(0) NULL DEFAULT NULL COMMENT '修改时间',
      `sys_org_code` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '所属部门',
      PRIMARY KEY (`id`) USING BTREE
    ) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

    -- ----------------------------
    -- Records of jmreport_test_user
    -- ----------------------------
    INSERT INTO `jmreport_test_user` VALUES ('1221980367267975170', '张三', 20, '2020-01-24 00:00:00', '1', 5000.00, 'admin', '2020-01-24 16:13:47', NULL, NULL, 'A01');
    INSERT INTO `jmreport_test_user` VALUES ('1221980404585332738', '李四', 21, '2020-01-07 00:00:00', '2', 6000.00, 'admin', '2020-01-24 16:13:56', NULL, NULL, 'A01');
    INSERT INTO `jmreport_test_user` VALUES ('1221980444433846273', '王五', 22, '2020-01-24 00:00:00', '1', 7000.00, 'admin', '2020-01-24 16:14:06', NULL, NULL, 'A02');
    INSERT INTO `jmreport_test_user` VALUES ('1221980482636443649', '赵六', 23, '2020-01-07 00:00:00', '2', 8000.00, 'admin', '2020-01-24 16:14:15', NULL, NULL, 'A02');
    INSERT INTO `jmreport_test_user` VALUES ('1221980518322966530', '钱七', 24, '2020-01-07 00:00:00', '1', 9000.00, 'admin', '2020-01-24 16:14:23', NULL, NULL, 'A03');
    INSERT INTO `jmreport_test_user` VALUES ('1221980554438574082', '周八', 25, '2020-01-24 00:00:00', '2', 10000.00, 'admin', '2020-01-24 16:14:32', NULL, NULL, 'A03');

    SET FOREIGN_KEY_CHECKS = 1;